version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./backend:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - mysql
  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
  # phpmyadmin:
  #   image: phpmyadmin
  #   ports:
  #     - '8888:80'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: strapi
  #     PMA_HOST: mysql
  #   depends_on: 
  #     - mysql